<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
    <div class="page-title">
        <h1><?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                <?php echo $this->__('Sign In or Create an Account') ?>
            <?php else: ?>
                <?php echo $this->__('Sign In'); ?>
            <?php endif; ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form autocomplete="off" action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="scaffold-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="col2-set">
            <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
            <div class="col-1 new-users">
                <div class="content">
                    <h2><?php echo $this->__('New Customers') ?></h2>
                    <p class="form-instructions"><?php echo $this->__('You must register in order to purchase B4Schools products.') ?></p>
                    <p class="form-instructions"><?php echo $this->__('Plus you’ll get:') ?></p>
                    <ul class="benefits">
                        <li><?php echo $this->__('Faster checkout.') ?></li>
                        <li><?php echo $this->__('Easy access to order status.') ?></li>
                        <li><?php echo $this->__('Order history, and quick reorder.') ?></li>
                        <li><?php echo $this->__('Advance notice on special offers and events.') ?></li>
                    </ul>
                </div>
                <div class="buttons-set">
                    <a title="<?php echo $this->__('Create Account') ?>" class="btn btn-primary" href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"><span><span><?php echo $this->__('Create Account') ?></span></span></a>
                </div>
            </div>
            <?php endif; ?>
            <?php // This column should be col-1 if the registration column is not displayed ?>
            <div class="<?php if ($this->helper('customer')->isRegistrationAllowed()): ?>col-2<?php else: ?>col-1<?php endif; ?> registered-users">
                <div class="content fieldset">
                    <h2><?php echo $this->__('Returning Customers') ?></h2>
                    <p class="form-instructions"><?php echo $this->__('If you already have an account, please sign in with your Username and Password below.') ?></p>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="form-control required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="form-control required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <li>
                            <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot your Password?') ?></a>
                        </li>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                </div>
                <div class="buttons-set">
                    <button type="submit" class="btn btn-primary" title="<?php echo $this->__('Sign In') ?>" name="send" id="send2"><span><span><?php echo $this->__('Sign In') ?></span></span></button>
                </div>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
