<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento professional edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="post">
    <div class="info-box">
        <div class="date">
            <?php $_date = strtotime($post->getCreatedTime()); ?>
            <strong><?php echo date('d', $_date) ?></strong>
            <span><?php echo date('F', $_date) ?></span>
        </div>
            <ul class="social-list">
                <!--li class="like-icon"><a href="#">891</a></li>
                <li> <a href="http://digg.com/submit?phase=2&amp;url=<?php echo $post->getAddress(); ?>&amp;title=<?php echo $post->getTitle(); ?>&amp;bodytext=<?php echo $post->getTitle(); ?>&amp;topic=" class="bm">
                    <img src="<?php echo Mage::getDesign()->getSkinUrl('aw_blog/images/communityIcons'); ?>/http-digg-com.gif" width="16" height="16" alt = "" /><br/><?php echo $this->__('Digg.com'); ?></a></li>
                <li><a href="http://www.stumbleupon.com/submit?url=<?php echo $post->getAddress(); ?>&amp;title=<?php echo $post->getTitle(); ?>&amp;newcomment=<?php echo $post->getTitle(); ?>" class="bm">
                    <img src="<?php echo Mage::getDesign()->getSkinUrl('aw_blog/images/communityIcons'); ?>/http-stumbleupon-com.gif" width="16" height="16" alt = "" /><br/><?php echo $this->__('Stumbleupon.com'); ?></a></li>
                <li><a href="http://del.icio.us/post/?url=<?php echo $post->getAddress(); ?>&amp;title=<?php echo $post->getTitle(); ?>&amp;notes=<?php echo $post->getTitle(); ?>" class="bm">
                    <img src="<?php echo Mage::getDesign()->getSkinUrl('aw_blog/images/communityIcons'); ?>/http-del-icio-us.gif" width="16" height="16" alt = "" /><br/><?php echo $this->__('Del.icio.us'); ?></a></li>
                <li><a href="http://www.google.com/bookmarks/mark?op=add&amp;bkmk=<?php echo $post->getAddress();?>&amp;title=<?php echo $post->getTitle();?>&amp;annotation=<?php echo $post->getTitle();?>&amp;cd=bm&amp;btnA=Add" class="bm">
                            <img src="<?php echo Mage::getDesign()->getSkinUrl('aw_blog/images/communityIcons'); ?>/http-google-com-bookmarks.gif" width="16" border="0" height="16"><br/>Google.com</a></li>
                <li><a href="http://www.facebook.com/sharer.php?u=<?php echo $post->getAddress(); ?>&amp;t=<?php echo $post->getTitle(); ?>" class="bm">
                    <img src="<?php echo Mage::getDesign()->getSkinUrl('aw_blog/images/communityIcons'); ?>/http-www-facebook-com-.gif" width="16" height="16" alt = "" /><br/><?php echo $this->__('Facebook'); ?></a></li>
                <li><a href="http://reddit.com/submit?url=<?php echo $post->getAddress(); ?>&amp;title=<?php echo $post->getTitle(); ?>" class="bm">
                    <img src="<?php echo Mage::getDesign()->getSkinUrl('aw_blog/images/communityIcons'); ?>/http-reddit-com.gif" width="16" height="16" alt = "" /><br/><?php echo $this->__('Reddit.com'); ?></a></li>
                <li class="share-icon"><a href="#">Share</a></li>
                -->
                
                
                <li><span class='st_facebook_large' displayText='Facebook'></span></li>
                <li><span class='st_googleplus_large' displayText='Google +'></span></li>
                <li><span class='st_twitter_large' displayText='Tweet'></span></li>
                <li><span class='st_pinterest_large' displayText='Pinterest'></span></li>
                <li><span class='st_linkedin_large' displayText='LinkedIn'></span></li>
                <li><span class='st_sharethis_large' displayText='ShareThis'></span></li>
            </ul>
            
            <script type="text/javascript">var switchTo5x=true;</script>
            <script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
            <script type="text/javascript">stLight.options({publisher: "3099af55-3ce7-4c72-9d8b-4186eb675147", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
    </div>
    <div class="holder">
        <h2><?php echo $post->getTitle(); ?></h2>
        <ul class="list">
            <li><?php echo $post->getUser(); ?></li>
            <?php $postCats = $post->getCats(); ?>
            <?php if (!empty($postCats)): ?>
                <li>
                <?php foreach ($postCats as $title => $url): ?>
                    <a href="<?php echo $url; ?>"><?php echo $title; ?></a>
                <?php endforeach; ?>
                </li>
            <?php endif; ?>
            <?php if ($this->getCommentsEnabled()): ?>
                <?php
                $_comments = 'Comments';
                if ($post->getCommentCount() == 1) {
                    $_comments = 'Comment';
                }
                ?>
                <li class="comments"><a href="<?php echo $post->getAddress(); ?>#commentBox"><?php echo Mage::helper('blog')->__('%s %s', $post->getCommentCount(), $_comments); ?></a></li>
            <?php endif; ?>
        </ul>
        <div class="std">
            <?php echo $post->getPostContent(); ?>
        </div>
        <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
    </div>
</div>

<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
    <?php $comments = $this->getComment(); ?>
    <div class="postTitle"><a name="commentBox" ></a>
        <h2><?php echo $this->__('Post Comments') ?></h2>
    </div>

    <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
        <?php foreach ($comments as $comment) : ?>
            <div class="commentWrapper">
                <div class="commentDetails"><h4 class="username"><?php echo $comment->getUser(); ?></h4> <?php echo $this->__("posted on") ?> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></div>
                <div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
            </div>
        <?php endforeach; ?>
     <?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>

<br/><br/>

    <?php if ($post->getComments()): ?>
        <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
        <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="" id="postComment" method="post">
                    <fieldset class="group-select">
                        <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                        <ul class="form-list">
                            <li>

                                <div class="input-box aw-blog-comment-area">
                                    <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                    <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:95%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="button-set" style="width:96%">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                        <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>

            <?php else: ?>
                <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
            <?php endif ?>

        <?php else: ?>

            <form action="" id="postComment" method="post">
                <fieldset class="group-select">
                    <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                    <ul class="form-list">
                        <li>
                            <div class="input-box">
                                <label for="name" class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label><br />
                                <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                            </div>

                            <div class="input-box">
                                <label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label><br />
                                <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
                            </div>

                            <div class="clear"></div>

                            <div class="input-box aw-blog-comment-area">
                                <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:95%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                            </div>
                        </li>

                        <?php
                        if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                            ?><li><?php
                require_once 'recaptcha/recaptchalib-aw.php';

                // Get a key from http://recaptcha.net/api/getkey
                $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                $error = null;

                echo recaptcha_get_html($publickey, $error);
                            ?></li><?php
            }
                        ?>
                    </ul>
                </fieldset>
                <div class="button-set" style="width:96%">
                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button class="button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                </div>
            </form>

            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>