<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
                <?php $_imgSize = 300; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <div class="product-primary">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>

                        <?php
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach($_nameAfterChildren as $_nameAfterChildName):
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                        ?>
                            <?php echo $_nameAfterChild->toHtml(); ?>
                        <?php endforeach; ?>
                    </div>
                    <div class="product-secondary">
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                    <div class="product-secondary">
                        <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                            <p class="action"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-primary btn-cart ajax-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                        <?php elseif($_product->isSaleable()): ?>
                            <p class="action"><a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span style="color:red"><?php echo $this->__('(Out of stock. Check back in 1-3 days)') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php $_product = Mage::getModel('catalog/product')->load($_product->getId());
            /*if ($i++%$_columnCount==0): ?>
            <?php endif*/ ?>
            <li class="item">
                <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
                    <?php if (date("Y-m-d") >= substr($_product->getNewsFromDate(), 0, 10) && date("Y-m-d") <= substr($_product->getNewsToDate(), 0, 10)): ?>
                        <span class="info-new"><?php echo $this->__('New') ?></span>
                    <?php endif; ?>
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <div class="product-info">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php if ($this->displayProductStockStatus()): ?>
                        <?php
                        if ($_product->isAvailable()) {
                            $num = (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty();
                            if ($_product->getTypeId() == 'simple' && $num<10) {
                                $_availability = '<span style="color:red">'.$this->__('(Just %s Left!)', $num).'</span>';
                            } else {
                                $_availability = $this->helper('catalog')->__('(In stock)');
                            }
                        } else {
                            $_availability = '<span style="color:red">'.$this->helper('catalog')->__('(Out of stock. Check back in 1-3 days)').'</span>';
                        }
                        ?>
                        <span calss="info" style="font-size: 12px;"><?php echo $_product->getCase()? "Sold in Case of ".$_product->getCase():''; ?></span>
                        <span class="info"><?php echo $_availability ?></span>
                    <?php endif; ?>
                    <div class="footer-panel">
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : 
                                
                                $hasProduct = false;
                                if (Mage::helper('customer')->isLoggedIn()) {
                                    $customer = Mage::getSingleton('customer/session')->getCustomer();
                                    $wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customer, true); 

                                    $wishlist = Mage::getModel('wishlist/item')->getCollection()
                                        ->addFieldToFilter('wishlist_id', $wishlist->getId())
                                        ->addFieldToFilter('product_id', $_product->getId());
                                    $wishlistitem = $wishlist->getFirstItem();
                                    $hasProduct = !is_null($wishlistitem->getId());
                                }
                                $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product);
                                if ($hasProduct) {
                                    $_wishlistSubmitUrl = str_replace('add','remove',$_wishlistSubmitUrl);
                                }
                                ?>
                                <li class="wishing-li <?php echo $hasProduct?' isWished':'' ?>">
                                    <a href="<?php echo $_wishlistSubmitUrl ?>" 
                                       class="link-wishlist"><?php echo $this->__( $hasProduct?'Remove from Wishlist':'Add to Wishlist' ) ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($_product->isSaleable()): ?>
                                <li><a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link-add<?php if (!$_product->canConfigure()) echo ' ajax-cart' ?>"><?php echo $this->__('Add to Cart') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </li>
            <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
        <?php endforeach ?>
    </ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar-bottom.phtml')->toHtml(); ?>
</div>
<?php endif; ?>

<?php
    //set product collection on after blocks
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach($_afterChildren as $_afterChildName):
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        $_afterChild->setProductCollection($_productCollection);
    ?>
    <?php echo $_afterChild->toHtml(); ?>
<?php endforeach; ?>
