<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
if (!function_exists('subparagraph')) {
    function subparagraph($paragraph = '', $start = 0, $length = 75) {
        $parts = explode(' ',(string)$paragraph);
        $parts = array_slice((array)$parts, $start, $length);
        return implode(' ',$parts)."&hellip;";
    }
}

?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
    <?php echo $this->getBlockHtml('formkey') ?>
    <div class="no-display">
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
    </div>
    <div class="page-title">
        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
    </div>
    <div class="product-holder">
        <?php echo $this->getChildHtml('media') ?>
        <div class="product-shop">
            <?php echo $this->getReviewsSummaryHtml($_product, 'default', false)?>
            <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>
            <div class="info-block">
                <dl class="info">
                    <?php if ($case = $_product->getCase()): ?>
                        <dt style="font-size: 12px;">Sold in Case of </dt>
                        <dd style="font-size: 12px;"><?php echo $case ?></dd>
                    <?php endif ?>
                    <?php echo $this->getChildHtml('product_type_availability'); ?>
                    <dt><?php echo $this->__('SKU') ?>:</dt>
                    <dd><?php echo $_product->getSku() ?></dd>
                </dl>
                <?php echo $this->getPriceHtml($_product); ?>
                <?php echo $this->getChildHtml('bundle_prices') ?>
                <?php echo $this->getTierPriceHtml() ?>
            </div>
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('other');?>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif; ?>
            <div class="add-to-cart-wrapper">
                <?php echo $this->getChildHtml('product_type_data') ?>
                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <span class="or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$_product->isSaleable()): ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>
                <?php echo $this->getChildHtml('sharing') ?>
            </div>
        </div>

        <?php echo $this->getChildHtml('related_products') ?>

        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    function openReviewForm(e){
        if (e.stopPropagation) e.stopPropagation();
        if (e.preventDefault) e.preventDefault();
        
        jQuery('a[href="#tab2"]').click();
        jQuery('html, body').animate({
                scrollTop: jQuery('#review-form').offset().top
            }, 1000);
        return false;
    };
    jQuery(document).ready(function(){
        jQuery('a[href*="review-form"]').bind('click', openReviewForm);
    });
    if (window.location.hash == '#review-form') {
        jQuery(document).ready(openReviewForm);
    }
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
               form.action = url;
            }
            var e = null;
            try {
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            // Remove custom datetime validators
            for (var methodName in Validation.methods) {
                if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                }
            }

            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
//]]>
</script>
<?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
        <?php $i = 0; ?>
        <div class="tabset-holder">
            <ul class="tabset">
            <?php foreach ($detailedInfoGroup as $alias => $html): ++$i; ?>
                <li><a<?php if ($i == 1) echo ' class="active"' ?> href="#tab<?php echo $i ?>"><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></a></li>
            <?php endforeach; ?>
            </ul>
        </div>
        <?php $i = 0; ?>
        <div class="tab-content">
            <?php foreach ($detailedInfoGroup as $alias => $html): ++$i; ?>
                <div id="tab<?php echo $i ?>"><?php echo $html ?></div>
            <?php endforeach;?>
        </div>
<?php endif; ?>
<?php echo $this->getChildHtml('upsell_products') ?>
<?php echo $this->getChildHtml('product_additional_data') ?>
