<?php
/**
 * Open Biz Ltd
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file OPEN-BIZ-LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mageconsult.net/terms-and-conditions
 *
 * @category   Magecon
 * @package    Magecon_Rma
 * @version    1.0.0
 * @copyright  Copyright (c) 2013 Open Biz Ltd (http://www.mageconsult.net)
 * @license    http://mageconsult.net/terms-and-conditions
 */
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $rma = $this->getRma() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('RMA #%s - %s', $rma->getRmaId(), $rma->getStatus()); ?></h1>
    <a href="<?php echo $this->getPrintUrl($rma) ?>" class="link-print" onclick="this.target='_blank';"><?php echo $this->__('Print RMA'); ?></a>

</div>
<p class="order-date"><?php echo $this->__('RMA Date: %s', $this->formatDate($rma->getCreationDate(), 'long')); ?></p>
<p class="order-date"><?php echo $this->__('RMA made from order #%s purchased on %s', $rma->getRealOrderId(), $this->formatDate($rma->getScanDate(), 'long')); ?></p>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Your Shipping Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $rma->getCustomerShippingAddress(); ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Merchant Shipping Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $rma->getMerchantShippingAddress(); ?></address>
            </div>
        </div>
    </div>
</div>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping information') ?></h2>
            </div>
            <div class="box-content">
                <?php echo Mage::getStoreConfig('rma/settings/shipping_information'); ?>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $rma->getShippingMethod() ?>
            </div>
        </div>
    </div>
</div>
<br />
<table class="data-table" id="my-orders-table" summary="<?php echo $this->__('Items Ordered') ?>">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><span class="nobr"><?php echo $this->__('Qty') ?></span></th>
            <?php
            $conditions = unserialize(Mage::getStoreConfig('rma/item_attributes_settings/condition'));
            if (!empty($conditions)):
                ?>
                <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Item Condition'); ?></th>
                <?php
            endif;
            $reasons = unserialize(Mage::getStoreConfig('rma/item_attributes_settings/reason'));
            if (!empty($reasons)):
                ?>
                <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Reason'); ?></th>
                <?php
            endif;
            $requests = unserialize(Mage::getStoreConfig('rma/item_attributes_settings/request'));
            if (!empty($requests)):
                ?>
                <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Request'); ?></th>
            <?php endif; ?>
<?php if (Mage::getStoreConfig('rma/item_attributes_settings/comment_enable') == 1): ?>
                <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Comment') ?></th>
        <?php endif; ?>
        </tr>
    </thead>
    <tbody>
            <?php foreach ($rma->getItems() as $_item): ?>
            <tr>
                <td align="left" style="font-size:13px; padding:3px 9px"><?php echo $_item->getProductName() ?></td>
                <td align="left" style="font-size:13px; padding:3px 9px"><?php echo $_item->getRmaQty() ?></td>
                <?php if (!empty($conditions)): ?>
                    <td align="left" style="font-size:13px; padding:3px 9px"><?php echo $_item->getCondition() ?></td>
                <?php endif; ?>
                <?php if (!empty($reasons)): ?>
                    <td align="left" style="font-size:13px; padding:3px 9px"><?php echo $_item->getReason() ?></td>
                <?php endif; ?>
                <?php if (!empty($requests)): ?>
                    <td align="left" style="font-size:13px; padding:3px 9px"><?php echo $_item->getRequestType() ?></td>
                <?php endif; ?>
                <?php if (Mage::getStoreConfig('rma/item_attributes_settings/comment_enable') == 1 && trim($_item->getComment()) != ""): ?>
                    <td align="left" style="font-size:13px; padding:3px 9px"><?php echo $_item->getComment() ?></td>
            <?php elseif (Mage::getStoreConfig('rma/item_attributes_settings/comment_enable') == 1 && trim($_item->getComment()) == ""): ?>
                    <td align="left" style="font-size:13px; padding:3px 9px"><?php echo "No comment" ?></td>
    <?php endif; ?>
            </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php $_history = $rma->getVisibleStatusHistory(); ?>
        <?php if (count($_history)): ?>
    <div class="order-additional order-comments">
        <h5><?php echo $this->__('About Your RMA') ?></h5>
        <dl class="order-about">
                <?php foreach ($_history as $_historyItem): ?>
                <dt><?php echo $this->formatDate($_historyItem->getCreationDate(), 'medium', true) ?>
                    <?php if (trim(Mage::getStoreConfig('rma/settings/rma_name')) != ''): ?>
                    <span class="separator">|</span><strong><?php echo Mage::getStoreConfig('rma/settings/rma_name'); ?>
        <?php endif; ?>
                    <dd><?php echo $this->escapeHtml($_historyItem->getComment()) ?></dd>
    <?php endforeach; ?>
        </dl>
    </div>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to My RMAs') ?></a></p>
</div>
<script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>