<?php if (isset($that)): ?>
<li class="fields">
    <div class="field field-password">
        <label for="password" class="required"><em>*</em><?php echo $that->__('Password') ?></label>
        <div class="input-box">
            <input type="password" name="password" id="password" title="<?php echo $that->__('Password') ?>" class="form-control input-text required-entry validate-password" />
        </div>
    </div>
    <div class="field field-password_confirmation">
        <label for="confirmation" class="required"><em>*</em><?php echo $that->__('Confirm Password') ?></label>
        <div class="input-box">
            <input type="password" name="confirmation" title="<?php echo $that->__('Confirm Password') ?>" id="confirmation" class="form-control input-text required-entry validate-cpassword" />
        </div>
    </div>
</li>


<li class="attribute_school starthidden">
    <p>Since you are registering as a school, we need just a little bit more information which will help us to better target products for you as well as manage inventory.</p>
</li>
<?php endif ?>