<?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Billing Address') ?><span class="changelink"><a
        href="#billing"
        onclick="checkout.changeSection('opc-billing'); return false;"><?php echo $this->__('Edit') ?></a></span>
</dt>
<dd class="complete">
    <address><?php echo $this->getBilling()->format('html') ?></address>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Billing Address') ?>
</dt>
<?php endif; ?>
