<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Payment Method') ?><span class="changelink"><a
        href="#payment"
        onclick="checkout.changeSection('opc-payment'); return false;"><?php echo $this->__('Edit') ?></a></span>
</dt>
<dd class="complete">
    <?php echo $this->getPaymentHtml() ?>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Payment Method') ?>
</dt>
<?php endif; ?>

