<?php
/**
 * One page checkout payment methods
 * 
 * @var $this Mage_Checkout_Block_Onepage_Payment_Methods
 */

$methods = $this->getMethods();
$revolution = false;
foreach ($methods as $key => $_method) {
    if ($_method->getCode() != 'revolution') continue;
    $revolution = $_method;
}
?>
<div style="margin-bottom:30px">
    <h3>Payment Method</h3>
</div>
<strong>B4Schools also accepts P-Cards or Purchase/Procurement Cards!</strong>
<?php echo $this->getPaymentMethodFormHtml($revolution) ?>
<hr/>

<?php 
/* PHASE 2 LAUNCH
 * 
<div style="margin-bottom:30px">
    <h3>Select School to Receive Credit For This Purchase</h3>
    <p>B4Schools will donate a portion of each purchase that has been credited to a specific school—directly to that school—in order to generate revenue for the items they need most. There are absolutely NO extra charges associated with your purchase(s). This selection is for tracking purposes only.</p>
</div>
<div class="form-list" style="margin-bottom:30px">
    <input type="text" class="input-text" name="donate_to_school" id="schoolinput"
               style="height:55px;padding:10px;font-size:16px;" placeholder="Start typing your school name"/>
</div>
<hr/>
*/ ?>

<div class="col2-right-layout form-list" style="margin-bottom:30px">
    <div class="main" style="min-height:0;">
        <div class="col-left sidebar">
            <h3>Discount Codes</h3>
        </div>
        <div class="col-xs-12" id="button_apply_coupon_success"></div>
    </div>
</div>

<div class="col2-right-layout form-list" style="margin-bottom:30px">
    <div class="row-fluid" style="min-height:0;">
        <div class="col-xs-12 col-md-10">
            <input type="text" class="input-text" name="discount_coupon" id="discount_coupon" 
               style="height:55px;padding:10px;font-size:16px;text-align:center" 
               placeholder="Enter Coupon Code"/>
        </div>
        <div class="col-xs-12 col-md-2">
            <button type="button" class="button" id="button_apply_coupon" style="height:55px;padding:10px;font-size:16px;">
                <span><span><?php echo $this->__('Apply') ?></span></span>
            </button>
        </div>
    </div>
    <div class="row-fluid" style="min-height:0;">
        <input type="checkbox" name="special_offers" class="input-checkbox" checked/>
        <span>Yes I'd like to be the first to know about special offers and events.</span>
    </div>
</div>

<span class="no-display"><input id="p_method_revolution" value="revolution" 
type="radio" name="payment[method]" checked="checked" class="radio" /></span>

<script type="text/javascript">
//<![CDATA[
jQuery(function(){
    <?php 
    // Getting an array of schools
    $schools = Mage::getResourceModel('datta_storelocator/store_collection'); 
    $sa = array();
    foreach($schools as $school) {
        $sa[] = array(
            'data' => $school->getData('entity_id'), 
            'value' => $school->getData('name'));
    }
    $lookups = json_encode($sa);
    ?>
    var countries = <?php echo $lookups ?>;
    jQuery('#schoolinput').autocomplete({
        lookup:countries
    });
    
    // adding the coupon injection for javascript
    jQuery('#button_apply_coupon').bind('click', function(e){
        e.preventDefault();
        jQuery.loadingbar({
            url: '<?php echo $this->getUrl('checkout/cart/couponPost') ?>',
            data: {
                payment_coupon_code: jQuery('#discount_coupon').val(),
                coupon_ajax: 'true'
            },
            success:function(data) {
                jQuery('#button_apply_coupon_success').html(data);
            }
        });
        
        return false;
    });
});
//]]>
</script> 