<?php
/**
 * "Grant Access" button
 *
 * @var $this Mage_Oauth_Block_Authorize_Button
 */
?>
<div>
    <div class="page-title">
        <h1><?php echo $this->__('Authorize application') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>

    <?php if (!$this->getHasException()): ?>
        <h2><?php echo $this->__('<strong>%s</strong> requests access to your account', $this->escapeHtml($this->getConsumer()->getName())); ?></h2>
        <p><?php echo $this->__('After authorization application will have access to you account.'); ?></p>
        <form id="oauth_authorize_confirm" action="<?php echo $this->getConfirmUrl() ?>" method="get">
            <input type="hidden" name="oauth_token" value="<?php echo $this->escapeHtml($this->getToken()) ?>">
            <button type="submit" class="btn btn-primary" title="<?php echo $this->__('Authorize') ?>" name="authorize">
                <span><span><?php echo $this->__('Authorize') ?></span></span></button>
        </form>
        <form id="oauth_authorize_reject" action="<?php echo $this->getRejectUrl() ?>" method="get">
            <input type="hidden" name="oauth_token" value="<?php echo $this->escapeHtml($this->getToken()) ?>">
            <button type="submit" class="btn btn-primary" title="<?php echo $this->__('Reject') ?>">
                <span><span><?php echo $this->__('Reject') ?></span></span></button>
        </form>
    <?php endif; ?>

</div>
