<?php
/**
 * Authorize rejection simple template
 *
 * @var $this Mage_Oauth_Block_AuthorizeBaseAbstract
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="page-title">
            <h1><?php echo $this->__('Rejection Of Authorization') ?></h1>
        </div>
        <div class="form-box">
            <div id="messages">
                <?php echo $this->getMessagesBlock()->toHtml() ?>
            </div>
            <button type="submit" class="btn btn-primary" onclick="window.close();" title="<?php echo $this->__('Close') ?>">
                <span><span><?php echo $this->__('Close') ?></span></span>
            </button>
        </div>
    </div>
</div>
